[package]
name = "pallet-supersig"
authors = ["Nathan GD <https://github.com/gdnathan>"]
description = "Pallet Supersig like multisig but with superpowers! Credit goes to Nathan GD for building, Timothee Delabro for supervising; Web3 Foundation and Edgeware for supporting, and Decentration as project and product design/management."
version = "0.1.0"
license = "Apache 2.0"
homepage = "https://decentration.org"
repository = "https://github.com/kabocha-network/pallet-supersig"
edition = "2021"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", features = ["derive"], default-features = false }
scale-info = { version = "1.0.0", default-features = false, features = ["derive"] }

frame-benchmarking = { git = "https://github.com/paritytech/substrate", default-features = false, optional = true, branch = "release-v0.9.23" }
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "release-v0.9.23" }
frame-system = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "release-v0.9.23" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "release-v0.9.23" }
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "release-v0.9.23" }
sp-core = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "release-v0.9.23" }

[dev-dependencies]
serde = { version = "1.0.132" }
sp-io = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "release-v0.9.23" }
pallet-balances = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "release-v0.9.23" }

[features]
default = ["std", "runtime-benchmarks"]
runtime-benchmarks = ["frame-benchmarking/runtime-benchmarks"]
std = [
	"codec/std",
    "sp-std/std",
    "sp-core/std",
    "sp-runtime/std",
	"scale-info/std",
    "pallet-balances/std",
	"frame-support/std",
	"frame-system/std",
	"frame-benchmarking/std",
]
try-runtime = [ "frame-support/try-runtime" ]
